### ISSUE TITLE
Regarding documentation and report file

### ISSUE THREAD

**Issue by riyasharma1408** [MohdSaif-1807/Network-Intrusion-Detection-System-Using-Machine-Learning-and-Deep-Learning#3]
Hey,
Can you please share a detailed report file on the NIDS project for better understanding.

**Comment by MohdSaif-1807** [comment]
I am attaching a short report which we have done during our project you can check that if you need specific details then let me know, I am attaching the document through this mail.
[NETWORK INTRUSION DETECTION SYSTEM.docx](https://github.com/MohdSaif-1807/Network-Intrusion-Detection-System-Using-Machine-Learning-and-Deep-Learning/files/14902015/NETWORK.INTRUSION.DETECTION.SYSTEM.docx)

**Comment by riyasharma1408** [comment]
Hi sir
Can you pls explain me the input and output of the dataset file and the
database design which will be made for MongoDB.
We have our presentation tomorrow, pls connect ASAP.

**Comment by MohdSaif-1807** [comment]
Hi mam, 
The thing is that how much I can provide publicly I have provided for more details you can mail me at saifmohd1807@gmail.com.
